apiVersion: sdk.platformspec.io/v1alpha1
kind: BlueprintSpec
metadata:
  name: example
spec:

  maturity: experimental
  authors:
    - name: Jens Saade
      email: jens@verticle.io

  description: -|
    this blueprint for Azure sets up a cluster, vnet and access groups for the cluster, as well as ArgoCD for deployments



