apiVersion: sdk.platformspec.io/v1alpha1
kind: Scaffold
metadata:
  name: backstage-action-create-repository-github
  labels:
    category: portal
    engine: backstage
    action: create-repository-github
spec:
  description: creates a new repository via a new RepositoryProviderResource
  bindingRef:
    kind: ServiceProviderBinding
    apiVersion: sdk.platformspec.io/v1alpha1
    name: platformscript
  buildSpec:
    template: template.kts
    subPath: manifests/portal/backstage/actions/create-repository-github
    entrypoint: "executeAction()"