apiVersion: sdk.platformspec.io/v1alpha1
kind: Scaffold
metadata:
  name: argocd
  labels:
    category: cicd
    engine: argocd
spec:
  implementing:
    singular: provider
    plural: providers
    group: core.platformspec.io
    version: v1alpha1
  description: creates an argocd instance with SSO to Azure EntraID
  bindingRef:
    kind: ServiceProviderBinding
    apiVersion: sdk.platformspec.io/v1alpha1
    name: platformscript
  buildSpec:
    template: manifests/cicd/argocd/template.kts
    entrypoint: "bootstrapProjectWorkflow()"