apiVersion: sdk.platformspec.io/v1alpha1
kind: Scaffold
metadata:
  name: azure-entraid
  labels:
    category: iaas
    engine: azure
    sso: entraid

spec:
  implementing:
    singular: provider
    plural: providers
    group: core.platformspec.io
    version: v1alpha1
  description: create necessary groups in Azure EntraID
  bindingRef:
    kind: ServiceProviderBinding
    apiVersion: sdk.platformspec.io/v1alpha1
    name: azure
  buildSpec: {}
