apiVersion: sdk.platformspec.io/v1alpha1
kind: Scaffold
metadata:
  name: backstage-templates
  labels:
    category: portal
    engine: backstage
    action: templates
spec:
  description: prepares and exports software templates from the platform spec to the portal
  builderRef:
    kind: ServiceProviderBinding
    apiVersion: sdk.platformspec.io/v1alpha1
    name: platformscript
  buildSpec:
    template: template.kts
    subPath: manifests/portal/backstage/templates/create-namespace
    entrypoint: "prepareTemplate()"