apiVersion: sdk.platformspec.io/v1alpha1
kind: Scaffold
metadata:
  name: argocd
  labels:
    category: repository
    engine: github
spec:
  implementing:
    singular: providerresource
    plural: providerresources
    group: sdk.platformspec.io
    version: v1alpha1
  description: manages a repository on Github
  bindingRef:
    kind: ServiceProviderBinding
    apiVersion: sdk.platformspec.io/v1alpha1
    name: githubrepository
  buildSpec: {}
