apiVersion: sdk.platformspec.io/v1alpha1
kind: Scaffold
metadata:
  name: hashivault
  labels:
    category: secrets
    engine: hashivault
spec:
  implementing:
    singular: providerresource
    plural: providerresources
    group: sdk.platformspec.io
    version: v1alpha1
  description: create a hashicorp vault instance
  bindingRef:
    kind: ServiceProviderBinding
    apiVersion: sdk.platformspec.io/v1alpha1
    name: containerized
  buildSpec:
    helmRepo: https://helm.releases.hashicorp.com
    chart: hashicorp/vault


