apiVersion: sdk.platformspec.io/v1alpha1
kind: Scaffold
metadata:
  name: hashivault
  labels:
    category: secrets
    engine: hashivault
spec:
  description: create a hashicorp vault instance
  builderRef:
    kind: ServiceProviderBinding
    apiVersion: sdk.platformspec.io/v1alpha1
    name: containerized
  buildSpec:
    helmRepo: https://helm.releases.hashicorp.com
    chart: hashicorp/vault


