apiVersion: sdk.platformspec.io/v1alpha1
kind: Skaffold
metadata:
  name: azure-entraid
  labels:
    category: iaas
    engine: azure
    sso: entraid

spec:
  description: create necessary groups in Azure EntraID
  builderRef:
    kind: Builder
    apiVersion: sdk.platformspec.io/v1alpha1
    name: azure
  buildSpec: {}

---
apiVersion: sdk.platformspec.io/v1alpha1
kind: Skaffold
metadata:
  name: hashivault
  labels:
    category: secrets
    engine: hashivault
spec:
  description: create a hashicorp vault instance
  builderRef:
    kind: Builder
    apiVersion: sdk.platformspec.io/v1alpha1
    name: containerized
  buildSpec:
    helmRepo: https://helm.releases.hashicorp.com
    chart: hashicorp/vault

---
apiVersion: sdk.platformspec.io/v1alpha1
kind: Skaffold
metadata:
  name: argocd
  labels:
    category: cicd
    engine: argocd
spec:
  description: creates an argocd instance with SSO to Azure EntraID
  builderRef:
    kind: Builder
    apiVersion: sdk.platformspec.io/v1alpha1
    name: platformscript
  buildSpec:
    template: template.kts
    entrypoint: "bootstrapProjectWorkflow()"