@import com.fasterxml.jackson.databind.JsonNode
@param JsonNode model
apiVersion: network.azure.upbound.io/v1beta1
kind: VirtualNetwork
metadata:
  name: ${model.get("metadata").get("name").asText()}
  namespace: platform
spec:
  forProvider:
    addressSpace:
      - ${model.get("spec").get("config").get("addressSpace").get(0).asText()}
    location: "West Europe"
    resourceGroupName: platform