apiVersion: sdk.platformspec.io/v1alpha1
kind: Scaffold
metadata:
  name: argocd
  labels:
    category: repository
    engine: github
spec:
  description: manages a repository on Github
  builderRef:
    kind: Builder
    apiVersion: sdk.platformspec.io/v1alpha1
    name: githubrepository
  buildSpec: {}
